server:
  port: 8080
  
spring:
  thymeleaf:
    mode: HTML5
    template-resolver-order: 0
    suffix: .html
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
  config:
    import:
      - classpath:pop_bill.yml
      - classpath:database.yml

file:
  dir: D:/test/

