package com.ld.user.vo;

import lombok.Data;

@Data
public class TendencyVO {
	private int tendency_seq;
	private int student_id;
	private String tendency_date;
	private String tendency_name;
	private float tendency_a1;
	private float tendency_a2;
	private float tendency_a3;
	private float tendency_a4;
	private float tendency_a5;
	private float tendency_a6;
	private float tendency_a7;
	private float tendency_a8;
	private float tendency_a9;
	private float tendency_a10;
	private float tendency_a11;
	private float tendency_a12;
	private float tendency_a13;
	private float tendency_h1;
	private float tendency_h2;
	private float tendency_h3;
	private float tendency_h4;
	private float tendency_h5;
	private float tendency_h6;
	private float tendency_h7;
	private float tendency_h8;
	private float tendency_h9;
	private float tendency_h10;
	private float tendency_h11;
	private float tendency_h12;
	private float tendency_h13;
	private float tendency_h14;
	private float tendency_r1;
	private float tendency_r2;
	private float tendency_r3;
	private float tendency_r4;
	private float tendency_r5;
	private float tendency_r6;
	private float tendency_e1;
	private float tendency_e2;
	private float tendency_e3;
	private float tendency_e4;
	private float tendency_e5;
	private float tendency_e6;
	private float tendency_e7;
	private float tendency_e8;
	private float tendency_e9;
	private float tendency_e10;
	private float tendency_e11;
	private float tendency_e12;
	private float tendency_e13;
	private float tendency_e14;
	private float tendency_e15;
	private float tendency_e16;
	private float tendency_e17;
	private float tendency_e18;
	private float tendency_e19;
}